miblog/urls.py
from django.conf.urls import url
from . import views

app_name = 'logictree'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    #conversores/bases
    url(r'^conversores/bases/$', views.bases, name='bases'),
    #conversores/ieee
    url(r'^conversores/ieee/$', views.ieee, name='ieee'),
    #evaluador
    url(r'^evaluador/$', views.evaluador, name='evaluador'),
    #graficador
    url(r'^graficador/$', views.graficador, name='graficador'),
    #/derivador
    url(r'^derivador/$', views.derivador, name='derivador'),
    #/biseccion
    url(r'^biseccion/$', views.biseccion, name='biseccion'),
    #/reglafalsa
    url(r'^reglafalsa/$', views.reglafalsa, name='reglafalsa'),
    #/newtonraphson
    url(r'^newtonraphson/$', views.newtonraphson, name='newtonraphson'),
    #secante
    url(r'^secante/$', views.secante, name='secante'),
    #/raices
    url(r'^raices/$', views.raices, name='raices'),
    #rectangulos
    url(r'^rectangulos/$', views.rectangulosview, name='rectangulosview'),
    #trapecio
    url(r'^trapecio/', views.trapecioview, name='trapecioview'),
    #simpson13
    url(r'^simpson13/$', views.simpson13view, name='simpson13view'),
    #simpson38
    url(r'^simpson38/$', views.simpson38, name='simpson38'),
    #montecarlo
    url(r'^montecarlo/$', views.montecarlo, name='montecarlo'),
    #conocenos
    url(r'^conocenos/$', views.conocenos, name='conocenos'),

    #CALCULOS

    #//
    url(r'^$', views.index, name='index'),
    #/braiture/conversores/bases
    url(r'^conversores/bases/calcular$', views.basescalc),
    #//conversores/ieee
    url(r'^conversores/ieee/calcular$', views.ieeecalc),
    #//evaluador
    url(r'^evaluador/calcular$', views.evaluadorcalc),
    #//graficador
    url(r'^graficador/calcular$', views.graficadorcalc),
    #//derivador
    url(r'^derivador/calcular$', views.derivadorcalc),
    #//biseccion
    url(r'^biseccion/calcular$', views.biseccioncalc),
    #//reglafalsa
    url(r'^reglafalsa/calcular$', views.reglafalsacalc),
    #//newtonraphson
    url(r'^newtonraphson/calcular$', views.newtonraphsoncalc),
    #//secante
    url(r'^secante/calcular$', views.secantecalc),
    #//raices
    url(r'^raices/calcular$', views.raicescalc),
    #//rectangulos
    #//simpson13
    #//simpson
    url(r'^simpson38/calcular$', views.simpson38calc),
    #//montecarlo
    url(r'^montecarlo/calcular$', views.montecarlocalc),
]

mysite/MetodosNumericos/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^brainture/', include('brainture.urls')),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
]

miblog/models.py
from django.db import models

# Create your models here.

miblog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .utilidades import conversores, ecuaciones, funciones
from .utilidades.integralesfin import *
from .utilidades.retangulos import *
from .utilidades.simpson import *
from json import JSONEncoder
from sympy import diff
import pdb

# Create your views here.

def index (request):
	context = {}
	return render(request, 'logictree/index.html', context)

def bases(request):
	context = {}
	return render(request, 'logictree/bases.html', context)

def ieee (request):
	context = {}
	return render(request, 'logictree/ieee.html', context)

def evaluador (request):
	context = {}
	return render(request, 'logictree/evaluador.html', context)

def graficador (request):
	context = {}
	return render(request, 'logictree/graficador.html', context)

def derivador (request):
	context = {}
	return render(request, 'logictree/derivador.html', context)

def biseccion (request):
	context = {}
	return render(request, 'logictree/biseccion.html', context)

def reglafalsa (request):
	context = {}
	return render(request, 'logictree/reglafalsa.html', context)

def newtonraphson (request):
	context = {}
	return render(request, 'logictree/newtonraphson.html', context)

def secante (request):
	context = {}
	return render(request, 'logictree/secante.html', context)

def raices (request):
	context = {}
	return render(request, 'logictree/raices.html', context)

def rectangulosview (request):
	if (request.method=='POST'):
		 funcion=request.POST['funcion']
		 a=request.POST['intervaloa']
		 b=request.POST['intervalob']
		 particiones=request.POST['npart']
		 mostrar=Rectangulos()
		 enviarIz=mostrar.recIzquierda(funcion,float(a),float(b),int(particiones))
		 enviarDe=mostrar.recDerecha(funcion,float(a),float(b),int(particiones))
		 enviarMe=mostrar.recMedios(funcion,float(a),float(b),int(particiones))
		 return render(request,'logictree/rectangulos.html',{"enviarIz":enviarIz,"enviarDe":enviarDe,"enviarMe":enviarMe} )
	else:
		enviarIz=""
		enviarDe=""
		enviarMe=""
	return render(request, 'logictree/rectangulos.html', {"enviarIz":enviarIz,"enviarDe":enviarDe,"enviarMe":enviarMe})

def trapecioview (request):
	if(request.method=='POST'):
		funcion=request.POST['funcion']
		a=request.POST['intervaloa']
		b=request.POST['intervalob']
		particiones=request.POST['npart']
		mostrar=Trap()
		print(funcion)
		print(a)
		print(b)
		print(particiones)
		enviar=mostrar.trapecios(funcion,float(a),float(b),int(particiones))
		return render(request,'logictree/trapecio.html',{"enviar":enviar})
	else:
		enviar=""
	return render(request, 'logictree/trapecio.html',{"enviar":enviar})

def simpson13view (request):
	if (request.method=='POST'):
		funcion=request.POST['funcion']
		a=request.POST['intervaloa']
		b=request.POST['intervalob']
		particiones=request.POST['npart']
		mostrar=Simp13()
		enviar=mostrar.simpin13(int(particiones),float(a),float(b),funcion)
		return render(request, 'logictree/simpson13.html', {"enviar":enviar})
	else:
		enviar=""
	return render(request, 'logictree/simpson13.html', {"enviar":enviar})

def simpson38 (request):
	context = {}
	return render(request, 'logictree/simpson38.html', context)

def montecarlo (request):
	context = {}
	return render(request, 'logictree/montecarlo.html', context)

def conocenos (request):
	context = {}
	return render(request, 'logictree/conocenos.html', context)


json = {'"nada"'}
#CALCULOOOOS
def basescalc(request):
	if request.method == 'POST':
		numero = request.POST['numero']
		base = request.POST['base']
		numeros = []
		numeros.append(base)
		if base == 'decimal':
			numeros.append(numero)
			numeros.append(conversores.decimalABinario(numero, 20))
			numeros.append(conversores.decimalAOctal(numero, 20))
			numeros.append(conversores.decimalAHexa(numero, 20))
		if base == 'binaria':
			numeros.append(conversores.binarioADecimal(numero))
			numeros.append(numero)
			numeros.append(conversores.decimalAOctal(conversores.binarioADecimal(numero), 20))
			numeros.append(conversores.decimalAHexa(conversores.binarioADecimal(numero), 20))
		if base == 'octal':
			numeros.append(conversores.octalADecimal(numero))
			numeros.append(conversores.decimalABinario(conversores.octalADecimal(numero), 20))
			numeros.append(numero)
			numeros.append(conversores.decimalAHexa(conversores.octalADecimal(numero), 20))
		if base == 'hexadecimal':
			numeros.append(conversores.hexaADecimal(numero))
			numeros.append(conversores.decimalABinario(conversores.hexaADecimal(numero), 20))
			numeros.append(conversores.decimalAOctal(conversores.hexaADecimal(numero), 20))
			numeros.append(numero)

		json = JSONEncoder().encode(numeros)

	return HttpResponse(json)

def ieeecalc (request):

	if request.method == 'POST':
		numero = request.POST['numero']
		representacion = request.POST['representacion']
		numeros = []
		numeros.append(representacion)
		if representacion == 'decimal':
			numeros.append(numero)
			numeros.append(conversores.binarioAPuntoFlotante32(conversores.decimalABinario(numero , 20)))
			numeros.append(conversores.binarioAPuntoFlotante64(conversores.decimalABinario(numero , 20)))
		if representacion == 'ieee32':
			numeros.append(conversores.binarioADecimal(conversores.puntoFlotanteABinario32(numero[0], numero[1:9], numero[9:32])))
			numeros.append(numero)
			numeros.append(conversores.binarioAPuntoFlotante64(conversores.puntoFlotanteABinario32(numero[0], numero[1:9], numero[9:32])))
		if representacion == 'ieee64':
			numeros.append(conversores.binarioADecimal(conversores.puntoFlotanteABinario64(numero[0], numero[1:12], numero[12:64])))
			numeros.append(conversores.binarioAPuntoFlotante32(conversores.puntoFlotanteABinario64(numero[0], numero[1:12], numero[12:64])))
			numeros.append(numero)

		json = JSONEncoder().encode(numeros)
	return HttpResponse(json)

def evaluadorcalc (request):
	resultado = []
	if request.method == 'POST':
		funcion = request.POST['funcion']
		x = request.POST['x']
		resultado.append(str(diff(funcion, 'x', 0).subs('x', x).evalf()))

		json = JSONEncoder().encode(resultado)

	return HttpResponse(json)

def graficadorcalc (request):
	context = {}
	return HttpResponse(json)

def derivadorcalc (request):
	resultado = []
	if request.method == 'POST':
		funcion = request.POST['funcion']
		x = request.POST['x']
		resultado.append(str(diff(funcion, 'x', 1)))
		resultado.append(str(diff(funcion, 'x', 1).subs('x', x).evalf()))
		resultado.append(str(diff(funcion, 'x', 2)))
		resultado.append(str(diff(funcion, 'x', 2).subs('x', x).evalf()))

		json = JSONEncoder().encode(resultado)

	return HttpResponse(json)

def biseccioncalc (request):
	if request.method == 'POST':
		funcion = request.POST['funcion']
		a = request.POST['a']
		b = request.POST['b']
		tolerancia = request.POST['tolerancia']
		print(funcion)
		print(a)
		print(b)
		print(tolerancia)
		resultado = ecuaciones.biseccion(str(funcion), a, b, tolerancia)

		json = JSONEncoder().encode(resultado)

	return HttpResponse(json)

def reglafalsacalc (request):
	if request.method == 'POST':
		funcion = request.POST['funcion']
		a = request.POST['a']
		b = request.POST['b']
		tolerancia = request.POST['tolerancia']
		print(funcion)
		print(a)
		print(b)
		print(tolerancia)
		resultado = ecuaciones.reglaFalsa(str(funcion), a, b, tolerancia)

		print(resultado)
		json = JSONEncoder().encode(resultado)

	return HttpResponse(json)

def newtonraphsoncalc (request):
	if request.method == 'POST':
		funcion = request.POST['funcion']
		x0 = request.POST['x0']
		error = request.POST['error']
		print(funcion)
		print(x0)
		print(error)
		resultado = ecuaciones.newtonRaphson(str(funcion), x0, error)

		print(resultado)
		json = JSONEncoder().encode(resultado)

	return HttpResponse(json)

def secantecalc (request):
	if request.method == 'POST':
		funcion = request.POST['funcion']
		a = request.POST['a']
		b = request.POST['b']
		tolerancia = request.POST['tolerancia']
		print(funcion)
		print(a)
		print(b)
		print(tolerancia)
		resultado = ecuaciones.secante(str(funcion), a, b, tolerancia)

		json = JSONEncoder().encode(resultado)
	return HttpResponse(json)

def raicescalc (request):
	if request.method == 'POST':
		funcion = request.POST['funcion']
		print(funcion)
		resultado = ecuaciones.raicesPolinomicas(str(funcion))
		json = JSONEncoder().encode(resultado)
	return HttpResponse(json)


def simpson38calc (request):
	context = {}
	return HttpResponse(json)

def montecarlocalc (request):
	context = {}
	return HttpResponse(json)

miblog/templates/logictree/base.html
{% load staticfiles %}

{% csrf_token %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block 'title' %}logictree{% endblock 'title' %}</title>
  <link rel="stylesheet" type="text/css" href= {% static 'logictree/styles/basestyles.css' %}>
  {% block 'styles' %}
  {% endblock 'styles' %}
</head>
<body>
  <div id="header">

  <ul id="nav_bar_ul">
    <div id="nav_bar_div">
      <li id="logo_inicio">
          <a href={% url 'logictree:index' %}>
              lo
          </a>
      </li>
      <li class="dropdown"><a class="dropdown_btn" href="#">Conversor</a>
        <div class="dropdown_menu">
          <a href={% url 'logictree:bases' %}>Bases numéricas</a>
          <a href={% url 'logictree:ieee' %}>Estandar IEEE 754 (64 y 32 bits)</a>
        </div>
      </li>
      <li><a href={% url  'logictree:evaluador' %}>Evaluador</a></li>
      <li><a href={% url 'logictree:graficador' %}>Graficador</a></li>
      <li><a href={% url 'logictree:derivador' %}>Derivada</a></li>
      <li class="dropdown"><a class="dropdown_btn" href="#">Ecuaciones</a>
        <div class="dropdown_menu">
          <a href={% url 'logictree:biseccion' %}>Bisección</a>
          <a href={% url 'logictree:reglafalsa' %}>Regla falsa</a>
          <a href={% url 'logictree:newtonraphson' %}>Newton Raphson</a>
          <a href={% url 'logictree:secante' %}>Secante</a>
          <a href={% url 'logictree:raices' %}>Raices de polinomios</a>
        </div>
      </li>
      <li class="dropdown"><a class="dropdown_btn" href="#">Integrales</a>
        <div class="dropdown_menu">
          <a href={% url 'logictree:rectangulosview' %}>Rectángulos</a>
          <a href={% url 'logictree:trapecioview' %}>Trapecio</a>
          <a href={% url 'logictree:simpson13view' %}>Simpson 1/3</a>
          <a href={% url 'logictree:simpson38' %}>Simpson 3/8</a>
          <a href={% url 'logictree:montecarlo' %}>Montecarlo</a>
        </div>
      </li>
      <li id="conocenos"><a href={% url   'logictree:conocenos' %}>Conóncenos</a></li>
    </div>
  </ul>
  {% block 'content' %}
  {% endblock 'content' %}
  <script type="text/javascript" src={% static 'logictree/libs/jquery-3.2.0.min.js' %}></script>
  <script type="text/javascript" src={% static 'logictree/scripts/commonscripts.js' %}></script>
  <script type="text/javascript" src={% static 'logictree/scripts/ajaxcsrfsetup.js' %}></script>
  {% block 'scripts' %}
  {% endblock 'scripts' %}
</body>
</html>

miblog/templates/logictree/biseccion.html
{% extends 'logictree/base.html' %}

{% load staticfiles %}

{% block 'title' %}
	Bisección
{% endblock 'title' %}

{% block 'content' %}
	<div id="div_contenido">
		<div class="container">
			<p class="texto_titulo">Método de biseccion</p>
			<hr class="lineaDeSeparacion">
			<form method="get">
				<div class="form-input">
					<p class="nombre_input">F(x)</p>
					<input id="i_funcion" type="text" placeholder="" class="funcion">
				</div>
				<div class="form-input">
					<p class="nombre_input">a</p>
					<input id="i_a" type="text" placeholder="" class="decimal">
				</div>
				<div class="form-input">
					<p class="nombre_input">b</p>
					<input id="i_b" type="text" placeholder="" class="decimal">
				</div>
				<div class="form-input">
					<p class="nombre_input">Error de tolerancia</p>
					<input id="i_err" type="text" placeholder="" class="decimal">
				</div>
				<div class="form-input">
					<p class="nombre_input">Resultado</p>
					<input id="i_resultado" type="text" placeholder="" disabled="true">
				</div>
			</form>
			<button type="submit" id="btnCalcular" name="btnCalcular" value="Calcular">
			<button type="submit "id="btnLimpiar" class="button" name="Limpiar">
		</div>
		<div class="container">
			<p class="inline titulo_tabla1">I, raiz, error</p>
			<div id="div_tabla">

			</div>
		</div>
		<div class="container">
			<div class="link_container">
				<a href= {% static 'logictree/pdf/' %} target="blank" class="button" >método de bisección</a>
			</div>
		</div>
		<div class="container">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/suQwXZDI2Eg" frameborder="0" allowfullscreen></iframe>
		</div>
	</div>
{% endblock 'content' %}

{% block 'scripts' %}
	<script type="text/javascript" src= {% static 'logictree/scripts/biseccionscripts.js' %} ></script>
{% endblock 'scripts' %}

miblog/templates/logictree/conocenos.html
{% extends 'brainture/base.html' %}

{% load staticfiles %}

{% block 'styles' %}
	<link rel="stylesheet" type="text/css" href= {% static 'brainture/styles/conocenosstyles.css' %}>
{% endblock 'styles' %}

{% block 'title' %}
	Conócenos
{% endblock 'title' %}

{% block 'content' %}
	<div id="div_contenido">
		<div class="container2">
			<p class="texto_titulo">¿Quienes somos?</p>
			<hr class="lineaDeSeparacion"></hr>		
			<p class="texto_parrafo">Somos 4 estudiantes de la <STRONG>Universidad San Buenaventura Cali</STRONG> de <STRONG>Ingeniería Multimedia</STRONG> e <STRONG>Ingeniería de Sistemas</STRONG> trabajando en conjunto para lograr este curso de métodos numéricos llamado <STRONG><em>Brainture</em></STRONG>.</p>			
			<div class="div_integrante">
				<div class="div_foto">
					<img class="img_conocenos" src= {% static 'brainture/imagenes/fotoPrueba.jpg' %} >
					<p>Juan Camilo Duque Delgado</p>
					<div class="div_parrafo_conocenos">
						
					</div>
					<div class="div_parrafo_conocenos">
						<p class="texto_parrafo2">Estudiante de Ingeniería Multimedia</p>
					</div>
				</div>	
			</div>
			<div class="div_integrante">
				<div class="div_foto">
					<img class="img_conocenos" src= {% static 'brainture/imagenes/fotoPrueba.jpg' %} >
					<div class="div_parrafo_conocenos">
						<p>Camilo Salguero Marín</p>
					</div>
					<div class="div_parrafo_conocenos">
						<p class="texto_parrafo2">Estudiante de Ingeniería Multimedia</p>
					</div>
				</div>
			</div>
			<div class="div_integrante">	
				<div class="div_foto">
					<img class="img_conocenos" src= {% static 'brainture/imagenes/fotoPrueba.jpg' %} >
					<div class="div_parrafo_conocenos">
						<p>Karym Lizeth Correa Diosa</p>
					</div>
					<div class="div_parrafo_conocenos">
						<p class="texto_parrafo2">Estudiante de Ingeniería Multimedia</p>
					</div>
				</div>	
			</div>
			<div class="div_integrante">
				<div class="div_foto">
					<img class="img_conocenos" src= {% static 'brainture/imagenes/fotoPrueba.jpg' %} >
					<div class="div_parrafo_conocenos">
						<p>Alejandro Beltrán</p>
					</div>
					<div class="div_parrafo_conocenos">
						<p class="texto_parrafo2">Estudiante de Ingeniería de Sistemas</p>
					</div>
				</div>
			</div>				
		</div>
	</div>
{% endblock 'content' %}

miblog/templates/logictree/derivador.html
{% extends 'logictree/base.html' %}

{% load staticfiles %}

{% block 'title' %}
	Derivador
{% endblock 'title' %}

{% block 'content' %}
	<div id="div_contenido">
		<div class="container">
			<p class="texto_titulo">Derivador de funciones</p>
			<hr class="lineaDeSeparacion">
			<form method="get">
				<div class="form-input">
					<p class="nombre_input">F(x)</p>
					<input id="i_funcion" type="text" placeholder="" class="funcion">
				</div>
				<div class="form-input">
					<p class="nombre_input">X</p>
					<input id="i_x" type="text" placeholder="" class="decimal">
				</div>
				<div class="form-input">
					<p class="nombre_input">F'(x)</p>
					<input id="i_r1" type="text" placeholder="" class="funcion" disabled="true">
				</div>
				<div class="form-input">
					<p class="nombre_input">Evaluada en X</p>
					<input id="i_r2" type="text" placeholder="" class="decimal" disabled="true">
				</div>
				<div class="form-input">
					<p class="nombre_input">F''(x)</p>
					<input id="i_r3" type="text" placeholder="" class="funcion" disabled="true">
				</div>
				<div class="form-input">
					<p class="nombre_input">Evaluada en X</p>
					<input id="i_r4" type="text" placeholder="" class="decimal" disabled="true">
				</div>
			</form>
			<button type="submit" id="btnCalcular" name="btnCalcular" value="Calcular">
			<button type="submit "id="btnLimpiar" class="button" name="Limpiar">
		</div>
	</div>
{% endblock 'content' %}

{% block 'scripts' %}
	<script type="text/javascript" src= {% static 'logictree/scripts/derivadorscripts.js' %} ></script>
{% endblock 'scripts' %}

miblog/templates/logictree/evaluador.html
{% extends 'logictree/base.html' %}

{% load staticfiles %}

{% block 'title' %}
	Evaluador
{% endblock 'title' %}

{% block 'content' %}
	<div id="div_contenido">
		<div class="container">
			<p class="texto_titulo">Evaluador de expresiones</p>
			<hr class="lineaDeSeparacion">
			<form method="get">
				<div class="form-input">
					<p class="nombre_input">F(x)</p>
					<input id="i_funcion" type="text" placeholder="Ingrese una función que dependa de x" class="funcion">
				</div>
				<div class="form-input">
					<p class="nombre_input">X</p>
					<input id="i_x" type="text" placeholder="Ingrese el valor de x" class="decimal">
				</div>
				<div class="form-input">
					<p class="nombre_input">Resultado</p>
					<input id="i_resultado" type="text" placeholder="" disabled="true">
				</div>
			</form>
			<button type="submit" id="btnCalcular" name="btnCalcular" value="Calcular">
		
		</div>
	</div>
{% endblock 'content' %}

{% block 'scripts' %}
	<script type="text/javascript" src= {% static 'logictree/scripts/evaluadorscript.js' %} ></script>
{% endblock 'scripts' %}

miblog/templates/logictree/rectangulos.html
{% extends 'logictree/base.html' %}



{% block 'title' %}
	Rectangulos
{% endblock 'title' %}

{% block 'content' %}
<form action="{% url 'logictree:rectangulosview' %}" method="POST">

  {% csrf_token %}

  <div >
      <h2>Metodo de integracion por rectangulos</h2>
      <br></br>
      <label for="funcion"><strong>Funcion:</strong>

      <input type="text" value="" id="funcion" name="funcion"></label>

      <br></br>
      <label for="intervaloa"><strong>Intervalo superior:</strong>
      <input type="text" value="" id="intervaloa" name="intervaloa"></label>
      <br></br>
      <label for="intervalob"><strong>Intervalo Inferior:</strong>
      <input type="text" value="" id="intervalob" name="intervalob"></label>
      <br></br>
      <label for="npart"><strong>numero de particiones:</strong>
      <input type="text" value="" id="npart" name="npart"></label>
      <br></br>

  </div>
  <div class="btns"><a><input type="Submit" value="Convertir"/></a><input type="Submit" value="Limpiar"/></div>
		<a href="https://www.geogebra.org/graphing">graficar mientras</a>
	<br></br><br></br>
  <tbody>
    {% if enviarIz %}
    <tr>
      <td>la integral es por izquierda es:</td>
      <td>{{enviarIz}}</td>
    </tr>
    {% endif %}
    <br>

    {% if enviarDe %}
    <tr>
      <td>la integral por derecha es:</td>
      <td>{{enviarDe}}</td>
    </tr>
    {% endif %}
    <br>

    {% if enviarMe %}
    <tr>
      <td>la integral por el medio es :</td>
      <td>{{enviarMe}}</td>
    </tr>
    {% endif %}


  </tbody>

</form>

<br></br><br></br><br></br>

{% endblock 'content' %}

miblog/templates/logictree/simpson13.html
{% extends 'logictree/base.html' %}

{% load staticfiles %}

{% block 'title' %}
	Simpson 1/3
{% endblock 'title' %}

{% block 'content' %}
<form action="{% url 'logictree:simpson13view' %}" method="POST">
{% csrf_token %}

<div >
		<h2>Metodo de integracion Simpson 1/3</h2>
		<br></br>
		<label for="funcion"><strong>Funcion:</strong>

		<input type="text" value="" id="funcion" name="funcion"></label>

		<br></br>
		<label for="intervaloa"><strong>Intervalo superior:</strong>
		<input type="text" value="" id="intervaloa" name="intervaloa"></label>
		<br></br>
		<label for="intervalob"><strong>Intervalo Inferior:</strong>
		<input type="text" value="" id="intervalob" name="intervalob"></label>
		<br></br>
		<label for="npart"><strong>numero de particiones:</strong>
		<input type="text" value="" id="npart" name="npart"></label>
		<br></br>

</div>
<div ><a><input type="Submit" value="Convertir"/></a><input type="Submit" value="Limpiar"/></div>
	<a href="https://www.geogebra.org/graphing">graficar mientras</a>
<br></br><br></br>
<tbody>
	{% if enviar %}
	<tr>
		<td>la integral es:</td>
		<td>{{enviar}}</td>
	</tr>
	{% endif %}
</tbody>

</form>

<br></br><br></br><br></br>
{% endblock 'content' %}

miblog/templates/logictree/trapecio.html
{% extends 'logictree/base.html' %}

{% block 'title' %}
	Trapecio
{% endblock 'title' %}

{% block 'content' %}
<form action="{% url 'logictree:trapecioview' %}" method="POST">
	{% csrf_token %}
	<div>
 		<h2>metodo de integracion por trapecios</h2>
		<br></br>
		<label for="funcion"><strong>funcion:</strong>
		<input type="text" value="" id="funcion" name="funcion"></label>
		<br></br>
		<br></br>
		<label for="funcion"><strong>intervalo superior:</strong>
		<input type="text" value="" id="intervaloa" name="intervaloa"></label>
		<br></br>
		<br></br>
		<label for="funcion"><strong>intervalo inferior:</strong>
		<input type="text" value="" id="intervalob" name="intervalob"></label>
		<br></br>
		<br></br>
		<label for="funcion"><strong>numero de particiones:</strong>
		<input type="text" value="" id="npart" name="npart"></label>
		<br></br>
	</div>
	<a><input type="submit" value="convertir"/></a>
	<input type="submit" value="limpiar"/>
	<a href="https://www.geogebra.org/graphing">graficar mientras</a>
	<div>
	</div>
	<br></br><br></br>
	<tbody>
		{% if enviar %}
		<tr>
			<td>la intrgral es:</td>
			<td> {{enviar}}</td>
		</tr>
		{% endif %}
	</tbody>
</form>
	<br></br><br></br>
{% endblock  %}